using System;
using System.Collections.Generic;

namespace FibonacciSequence
{
    class Program
    {
        static void Main(string[] args)
        {
            /*Each new term in the Fibonacci sequence is generated by adding the previous two numbers.
              By starting with 1 and 2, the first 10 numbers will be:
              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

              By considering the terms in the Fibonacci sequence whose values do not exceed four million,
              find the sum of the even-valued terms.
            */

            int firstNumber = 0;
            int secondNumber = 1;
            int total = 0;
            int sum = 0;
            List<int> listOfEvenNumbers = new List<int>();

            for (int i = 0; i < 50; i++)
            {
                total = firstNumber + secondNumber;     // first plus second number
                firstNumber = secondNumber;             // keep track of the previous second number
                secondNumber = total;                   // replace the second number

                if (total < 4_000_000)
                {
                    Console.WriteLine(total);
                }
                else
                {
                    break;
                }

                if (total % 2 == 0)
                {
                    listOfEvenNumbers.Add(total);
                    sum += total;
                }
            }

            Console.WriteLine();

            foreach (int number in listOfEvenNumbers)
            {
                Console.WriteLine(number);
            }
            Console.WriteLine("\nThe sum of all even Fibonacci numbers is: " + sum);
        }
    }
}
